[target.aarch64-linux-android]
ar = "C:/Users/sddrk/AppData/Local/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar.exe"
linker = "C:/Users/sddrk/AppData/Local/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe"
rustflags = ["-C", "link-arg=--target=aarch64-linux-android24"]

[target.armv7-linux-androideabi]
ar = "C:/Users/sddrk/AppData/Local/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar.exe"
linker = "C:/Users/sddrk/AppData/Local/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe"
rustflags = ["-C", "link-arg=--target=armv7a-linux-androideabi24"]

[target.x86_64-linux-android]
ar = "C:/Users/sddrk/AppData/Local/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar.exe"
linker = "C:/Users/sddrk/AppData/Local/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe"
rustflags = ["-C", "link-arg=--target=x86_64-linux-android24"]

[target.i686-linux-android]
ar = "C:/Users/sddrk/AppData/Local/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar.exe"
linker = "C:/Users/sddrk/AppData/Local/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe"
rustflags = ["-C", "link-arg=--target=i686-linux-android24"]
